### ISSUE TITLE
Script for training

### ISSUE THREAD

**Issue by manapshymyr-OB** [radiantearth/model_ecaas_agrifieldnet_gold#7]
Thanks for the interesting model. I am curious about where to find the script to train.

**Comment by guidorice** [comment]
@manapshymyr-OB thanks for your inquiry. The complete winning solution from the competition, which should include training scripts, is in a .zip file ([see bottom of documentation page here](https://github.com/radiantearth/model_ecaas_agrifieldnet_gold/blob/main/docs/index.md)).
